### ISSUE TITLE
missing csv files

### ISSUE THREAD

**Issue by listener17** [eloimoliner/bwe_historical_recordings#2]
Several places in the code, I see pointer to csv files. 
These csv files seems to be not available in the repository?

**Comment by eloimoliner** [comment]
Which csv files are you referring to? Is it the gramophone noise dataset? 
The dataset and its info.csv should be available here:
http://research.spa.aalto.fi/publications/papers/icassp22-denoising/

**Comment by listener17** [comment]
Okay, I think you answered it (partly)?
I meant, info.csv and audio_files.txt
https://github.com/eloimoliner/bwe_historical_recordings/blob/main/conf/dset/pianos.yaml
(also: what's the difference between path_music_test and path_test?)

and, butter_filters.csv here:
https://github.com/eloimoliner/bwe_historical_recordings/blob/main/conf/conf.yaml

**Comment by eloimoliner** [comment]
Hi,

I think you will not need these files, only the info.csv for the noises. I had them in a previous version of the code, but then I didn't use them.

path_test is also unused, you only have to care about path_music_train, path_music_validation and path_noises

Again, I'm sorry, this is just a research-oriented code, so it may not be very polished. I'll try to delete all the unused functions and variables to avoid confussion.
